version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: slim:latest
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
            COMPOSER_ALLOW_SUPERUSER: 1
            APP_DEBUG: "true"
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: hexaland
            DB_USERNAME: root
            DB_PASSWORD: password
            REDIS_CACHE_HOST: redis
            REDIS_CACHE_PORT: 6379
            ENABLE_CORS: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
            - mysql
    mysql:
        container_name: hexaland_mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: hexaland
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"

    phpmyadmin:
        container_name: hexaland_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8181:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        volumes:
            - /sessions
        depends_on:
            - mysql
    redis:
        container_name: hexaland_redis
        image: redis:5